### ISSUE TITLE
이전 PR 코드 보완 & 음식(버거, 사이드 메뉴) 관련 코드 작성

### ISSUE THREAD

**Issue by canlion** [f-lab-edu/burger-map#15]
# 목표
* 이전 코드 보완
* 음식(버거, 사이드 메뉴) 관련 코드 작성

# 메모
1. 로그인 여부 확인은 컨트롤러에서, 회원이 OWNER 타입인지 확인은 서비스에서 수행하는데 자연스러운건지?
  - 그렇게 작성한 이유: 로그인 여부 확인은 이 서비스 내부로의 접근이 가능한지에 대한 확인이므로 컨트롤러 계층에 작성했고, 회원 타입 확인은 서비스 내부에서 회원 타입에 따라 사용 가능한 기능에 차등을 두기 위함이므로 서비스 계층에 작성함.
  - 핸들러마다 로그인 확인 코드가 중복되어 `@CheckLogin` 어노테이션이 붙은 핸들러 호출시 `LoginCheckInterceptor` 인터셉터에서 세션 속성을 확인해 로그인 확인하도록 수정. 인터셉터는 서블릿과 컨트롤러 사이에서 동작하니 비즈니스 로직으로 생각되는 회원 타입 확인을 인터셉터에서 수행하는 것은 어울리지 않는다고 생각됨.
  - 서비스 레이어에서는 AOP를 활용?
2. 버거와 사이드 메뉴를 하나의 테이블에 넣을지, 별개의 테이블에 넣을지
  - 버거는 패티 종류와 번 종류를 속성으로 포함하고, 사이드 메뉴는 메뉴 종류(감자튀김, 양파튀김, 맥주, ...)를 속성으로 포함.
  - 하나의 테이블에 관리
    - 버거 레코드는 메뉴 종류에 null, 사이드 메뉴는 패티 종류와 번 종류에 null
    - 테이블 수가 적다. 조회도 단순 / nullable한 컬럼이 있으므로 검증 로직 필요, 조회 후 속성의 null 여부에 따라 버거 또는 사이드메뉴를 판별해야함
  - 별개의 테이블에 관리
    - nullable 컬럼 없음
    - nullable에 대한 검증 로직 불필요, 조회 후 버거 또는 사이드 메뉴 판별이 불필요, 테이블의 의미가 명확함 / 테이블 수가 늘어난다. 별개의 ID 공간을 가지게 되어 리뷰에 버거에 대한 리뷰인지, 사이드메뉴에 대한 리뷰인지 표시가 필요

**Comment by canlion** [comment]
# 2. 버거와 사이드 메뉴를 하나의 테이블에 넣을지, 별개의 테이블에 넣을지

## JPA 상속 전략
* [Inheritance Strategies with JPA and Hibernate – The Complete Guide](https://thorben-janssen.com/complete-guide-inheritance-strategies-jpa-hibernate/)

상속은 자바의 핵심 컨셉 중 하나. 당연히 개발자들은 상속을 도메인 모델에도 사용하고 싶다. 하지만 RDB는 상속 개념을 지원하지 않는다. 그래서 JPA의 구현들은 상속 구조를 하나 이상의 테이블에 맵핑하는 전략을 지원한다.

### Mapped Superclass

* 각 엔티티는 개별 테이블에 맵핑되고, 모든 테이블이 부모의 속성을 포함한다.
* 부모는 엔티티가 아니므로 다형성 쿼리(ex - 모든 `Publication`을 조회나, `Author`를 통한 모든 종류의 `Publication` 조회)가 불가능하다. (엔티티마다 독립된 별도의 테이블을 가지므로)
	* 부모와 다른 엔티티간의 관계는 포함되지 않으므로 필요하다면 각 엔티티마다 그 관계를 설정해야한다.
		* 예시에서는 `Book`과 `BlogPost`에는 `Publication`과 `Author`의 관계가 포함되지 않음. 필요하면 `Book`과 `Author`의 관계, `BlogPost`와 `Author`의 관계를 직접 설정해야한다.
* 단순히 여러 엔티티가 같은 속성을 공유해야한다면 쉽게 사용할 수 있는 전략

### Table per Class

* mapped superclass와 유사하되 부모 클래스도 엔티티
	* 부모 클래스와 다른 엔티티간의 관계를 이용할 수 있어 다형성 쿼리 가능
		* UNION 연산을 하므로 성능 이슈가 생길 수 있다. 다형성 쿼리를 사용한다면 지양하도록.
	* 다만 실제로 부모 클래스의 테이블이 생성되지는 않음. 쿼리는 JPA가 알아서 해준다.
		* 실제 테이블을 갖지 않더라도 JPA가 엔티티로 인식하고 활용

### Single Table

* 모든 엔티티를 하나의 테이블에 맵핑
	* 각 엔티티가 컬럼의 일부만을 사용하고 나머지는 null 처리
		* 데이터 무결성 이슈를 발생시킬 수 있다
		* 모든 엔티티가 공유하는 컬럼만이 NotNull 설정 가능
	* 레코드가 어떤 엔티티인지 나타내기 위해 discriminator column을 이용(엔티티 속성은 아님)
		* 특정 엔티티 조회시 discriminator column의 값이 특정 엔티티인 경우를 조회
* 다형성 쿼리가 효율적이고 일반적으로 가장 좋은 성능

### Joined

* 부모 클래스, 자식 클래스 모두 개별 테이블에 맵핑
	* 공통 속성인 부모 클래스의 속성은 부모 클래스의 테이블에 맵핑, 자식 클래스 엔티티는 자신의 속성만 테이블에 맵핑
	* 부모 클래스의 테이블의 레코드와 자식 클래스 테이블의 레코드가 대응되며 PK를 공유한다.
* 쿼리는 join 연산 수행

### 어떤 전략을?
* 다형성 쿼리의 최고 퍼포먼스: single table 전략
	* 단, 데이터 무결성에 주의. 엔티티간의 공통 속성 외에는 NotNull을 사용할 수 없어 검증 로직 필요
* 성능보다는 데이터 일관성 + 다형성 쿼리: Joined 전략
* 엔티티간의 연관관계가 불필요하거나 다형성 쿼리 불필요:
	* 부모 클래스가 단순히 기술적 용도로 존재하는 경우: mapped superclass 전략
		* 부모 클래스가 단순히 코드의 중복을 줄이기 위한 용도로 작성되었고 미래에도 어떤 역할을 하지는 않으리라 예측되는 경우
	* 나중에라도 다형성 쿼리를 쓰지 않을까? - Table per Class 전략
		* 부모 클래스를 이용한 다형성 쿼리를 미래에 사용할 것 같다.

## 그래서

* `Food` 클래스 도입 - 버거와 사이드 메뉴의 공통 속성인 `storeId`, `name`, `price`, `introduction`을 포함하여 버거와 사이드메뉴가 `Food`를 상속
* 생각해 볼 조건
  - "가게의 모든 음식 조회"와 같은 다형성 쿼리가 필요
  - 버거나 사이드 메뉴에 식별 아이디를 통해 개별적으로 접근이 가능해야함
  - 버거와 사이드 메뉴가 같은 식별 아이디 공간을 공유하여 리뷰가 어떤 음식에 대한 리뷰인지를 속성으로 표현할 때 버거에 대한 리뷰인지, 사이드 메뉴에 대한 리뷰인지를 추가로 표시하고 싶지 않음.
* 그래서
  - Mapped Superclass 전략: 다형성 쿼리가 불가능
  - Table per Class 전략: 다형성 쿼리는 가능하되 버거와 사이드 메뉴가 개별 테이블을 갖고 PK 공간을 공유하지 않음
  - Single Table 전략: 다형성 쿼리 성능이 좋고 버거, 사이드 메뉴가 같은 PK 공간을 공유하되 데이터 무결성을 위한 추가적인 로직이 필요 (ex - 패티&번 속성과 메뉴 종류 속성은 배타적이어야 함, 버거라면 패티&번은 모두 NotNull, 모두 null이면 안됨, ...) - OK
  - Joined 전략: 다형성 쿼리가 가능하고, 버거와 사이드 메뉴가 개별 테이블을 갖되 Food 테이블을 통해 PK 공간 공유, 데이터 무결성을 위한 추가적인 검증 로직이 Single Table 만큼은 아닐 것. - OK
* 퍼포먼스가 중요하다고는 생각되지 않고, 검증 로직을 줄일 수 있는 Joined 전략이 좋아보인다.

**Comment by f-lab-lyan** [comment]
>서비스 레이어에서는 AOP를 활용?

기술적인 욕심으로 하는 것이라면, 괜찮은 것 같아요.
